/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg1;
import projectpl.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.*;
import serviceprovider.SERVICE_PROVIDER;
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        log_label1 = new javax.swing.JLabel();
        log_email = new javax.swing.JTextField();
        log_label2 = new javax.swing.JLabel();
        log_password = new javax.swing.JPasswordField();
        log_in = new javax.swing.JButton();
        create_account = new javax.swing.JButton();
        admin = new javax.swing.JRadioButton();
        customer = new javax.swing.JRadioButton();
        SP = new javax.swing.JRadioButton();
        PM = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        log_label1.setText("Email");
        getContentPane().add(log_label1);
        log_label1.setBounds(20, 56, 58, 45);

        log_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_emailActionPerformed(evt);
            }
        });
        getContentPane().add(log_email);
        log_email.setBounds(113, 65, 277, 26);

        log_label2.setText("Passowrd");
        getContentPane().add(log_label2);
        log_label2.setBounds(20, 110, 75, 44);

        log_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(log_password);
        log_password.setBounds(113, 119, 277, 26);

        log_in.setText("Log in");
        log_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_inActionPerformed(evt);
            }
        });
        getContentPane().add(log_in);
        log_in.setBounds(113, 221, 77, 29);

        create_account.setText("Create Account");
        create_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_accountActionPerformed(evt);
            }
        });
        getContentPane().add(create_account);
        create_account.setBounds(251, 221, 139, 29);

        buttonGroup1.add(admin);
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin);
        admin.setBounds(77, 174, 79, 29);

        buttonGroup1.add(customer);
        customer.setText("Customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        getContentPane().add(customer);
        customer.setBounds(174, 174, 101, 29);

        buttonGroup1.add(SP);
        SP.setText("SP");
        getContentPane().add(SP);
        SP.setBounds(364, 174, 51, 29);

        buttonGroup1.add(PM);
        PM.setText("PM");
        PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMActionPerformed(evt);
            }
        });
        getContentPane().add(PM);
        PM.setBounds(293, 174, 53, 29);

        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1, 0, 480, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_log_emailActionPerformed

    private void log_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_log_passwordActionPerformed

    private void log_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_inActionPerformed
        try {
            int role=0;
            int count=0;
            int right_role=0;
            int ID=0;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=EventMangment","root","123");
            String email = log_email.getText();
            String pass = log_password.getText();
            Statement st = con.createStatement();
            String sql = "SELECT COUNT(1) FROM account WHERE Email='"+email+"' and pass='"+pass+"' ";
            ResultSet re = st.executeQuery(sql);
            if(re.next()){
               count= re.getInt(1);
            }
            //System.out.println(count);
     
            if(admin.isSelected()){
            role = 1;
            }
            
            if(SP.isSelected()){
            role = 2;
            }
            
            if(PM.isSelected()){
            role = 3;
            }
            
            if(customer.isSelected()){
            role = 4;
            }
            Statement st2 = con.createStatement();
            String Sql2 ="SELECT * FROM account WHERE Email='"+email+"' and pass='"+pass+"'";
             ResultSet rs2 = st.executeQuery(Sql2);
            while(rs2.next()){
            right_role = rs2.getInt("job_id");
            }
            Statement st3 = con.createStatement();
            String sql4="Select ID from account where Email='"+email+"' ";
            ResultSet rs4 = st3.executeQuery(sql4);
            while(rs4.next()){
            ID=rs4.getInt("ID");
            }
            if(count==1 && role==right_role){
            JOptionPane.showMessageDialog(null,"Login successfully","Done",JOptionPane.INFORMATION_MESSAGE);
            switch(role){
               case(1):
                     Admin x = new Admin();
                     x.setLocation(420, 200);
                     x.setSize(1200,800);
                     x.setVisible(true);
                     this.dispose();
                     break;
                case(2):
                    SERVICE_PROVIDER test = new SERVICE_PROVIDER();
                    test.setVisible(true);
                    break;
                    
                case(3):
                    ProjectManager pm= new ProjectManager();
                    pm.setSize(1800,1200);
                    pm.setLocation(100,50);
                    pm.setVisible(true);
                     break;
                case (4):
                    custmer y = new custmer();
                    y.setLocation(100,50);
                    y.setSize(1800, 1200);
                    y.show();
                    this.dispose();
                    break;
                        }
            
            }
            
            else{
                  JOptionPane.showMessageDialog(null,"Email Or Password Are Invalid!!","Error",JOptionPane.ERROR_MESSAGE);
                    }
        } 
        catch (ClassNotFoundException ex) {
          //  Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null,"SQLServer Connector Not Found !","Error",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Email Or Password Are Invalid!!","Error",JOptionPane.ERROR_MESSAGE);
//Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_log_inActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMActionPerformed

    private void create_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_accountActionPerformed
        
        account acc = new account();
        acc.setLocation(480,200);
        acc.setSize(900,500);
        acc.setVisible(true);
        //acc.setResizable(true);
        this.dispose();
    }//GEN-LAST:event_create_accountActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton PM;
    private javax.swing.JRadioButton SP;
    private javax.swing.JRadioButton admin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton create_account;
    private javax.swing.JRadioButton customer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JTextField log_email;
    private javax.swing.JButton log_in;
    private javax.swing.JLabel log_label1;
    private javax.swing.JLabel log_label2;
    private javax.swing.JPasswordField log_password;
    // End of variables declaration//GEN-END:variables
}
